version: 1.0.{build}
image: Visual Studio 2019

install:
  - choco install msys2 --yes
  - set PATH=C:\tools\msys64\usr\bin;%PATH%
  - C:\tools\msys64\usr\bin\bash -lc "pacman -Syuu --noconfirm"
  - C:\tools\msys64\usr\bin\bash -lc "pacman -S --noconfirm mingw-w64-x86_64-gcc"

build_script:
  - set PATH=C:\tools\msys64\mingw64\bin;%PATH%
  - gcc --version
  - gcc -o microsocks.exe socks5srv.c sblist.c sblist_delete.c server.c

artifacts:
  - path: microsocks.exe
