version: 1.0.{build}
image: Visual Studio 2019

install:
  - choco install make --yes
  - refreshenv

build_script:
  - gcc -o microsocks.exe socks5srv.c sblist.c sblist_delete.c server.c

artifacts:
  - path: microsocks.exe
