version: 1.0.{build}
image: Visual Studio 2019

install:
  - choco install mingw --yes

build_script:
  - cmd: |
      set PATH=C:\ProgramData\chocolatey\lib\mingw\tools\install\bin;%PATH%
      gcc --version
      gcc -o microsocks.exe socks5srv.c sblist.c sblist_delete.c server.c

artifacts:
  - path: microsocks.exe
